/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import koneksi.koneksi;
/**
 *
 * @author USER
 */
public class menu_utama extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
        String admin = UserID.getNamaAdmin();
        label_selamatdatang.setText("Welcome, "+admin);
        tampilkanTanggal_hariini();
        tampilkanWaktuSekarang();
        waktuBerjalan();
    }
    
    private void tampilkanTanggal_hariini() {
        Date tanggalSaatIni = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE, dd-MM-yyyy");
        String tanggalFormatted = formatter.format(tanggalSaatIni);
        tanggal_label.setText(tanggalFormatted);
    }

    private void tampilkanWaktuSekarang() {
        Date waktuSaatIni = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
        String waktuFormatted = formatter.format(waktuSaatIni);
        jam_label.setText(waktuFormatted);
    }

    private void waktuBerjalan() {
        int delay = 1000;
        Timer waktu = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tampilkanWaktuSekarang();
            }
        });
        waktu.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label_selamatdatang = new javax.swing.JLabel();
        tanggal_label = new javax.swing.JLabel();
        jam_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mAdmin = new javax.swing.JMenuItem();
        mKaryawan = new javax.swing.JMenuItem();
        mPelanggan = new javax.swing.JMenuItem();
        mLayanan = new javax.swing.JMenuItem();
        mAntar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mCucimasuk = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        rAdmin = new javax.swing.JMenuItem();
        rKaryawan = new javax.swing.JMenuItem();
        rPelanggan = new javax.swing.JMenuItem();
        rLayanan = new javax.swing.JMenuItem();
        rPengantaran = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        rAkun = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_selamatdatang.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        label_selamatdatang.setForeground(new java.awt.Color(255, 255, 255));
        label_selamatdatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_selamatdatang.setText("Welcome");
        jPanel2.add(label_selamatdatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 60));

        tanggal_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggal_label.setForeground(new java.awt.Color(255, 255, 255));
        tanggal_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tanggal_label.setText("Tanggal Hari Ini");
        jPanel2.add(tanggal_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 0, 181, 25));

        jam_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jam_label.setForeground(new java.awt.Color(255, 255, 255));
        jam_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jam_label.setText("Jam Hari Ini");
        jPanel2.add(jam_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 31, 76, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo_menu.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 83, -1, -1));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/master.png"))); // NOI18N
        jMenu1.setText("Master");
        jMenu1.setFont(new java.awt.Font("Segoe UI Historic", 0, 15)); // NOI18N

        mAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        mAdmin.setText("Admin");
        mAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAdminActionPerformed(evt);
            }
        });
        jMenu1.add(mAdmin);

        mKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/karyawan.png"))); // NOI18N
        mKaryawan.setText("Karyawan");
        mKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKaryawanActionPerformed(evt);
            }
        });
        jMenu1.add(mKaryawan);

        mPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan.png"))); // NOI18N
        mPelanggan.setText("Pelanggan");
        mPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPelangganActionPerformed(evt);
            }
        });
        jMenu1.add(mPelanggan);

        mLayanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mLayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/layanan.png"))); // NOI18N
        mLayanan.setText("Layanan");
        mLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLayananActionPerformed(evt);
            }
        });
        jMenu1.add(mLayanan);

        mAntar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mAntar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/antar.png"))); // NOI18N
        mAntar.setText("Pengantaran");
        mAntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAntarActionPerformed(evt);
            }
        });
        jMenu1.add(mAntar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaksi.png"))); // NOI18N
        jMenu2.setText("Transaksi");
        jMenu2.setFont(new java.awt.Font("Segoe UI Historic", 0, 15)); // NOI18N

        mCucimasuk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mCucimasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cucian.png"))); // NOI18N
        mCucimasuk.setText("Cucian Masuk");
        mCucimasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCucimasukActionPerformed(evt);
            }
        });
        jMenu2.add(mCucimasuk);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report.png"))); // NOI18N
        jMenu3.setText("Report");
        jMenu3.setFont(new java.awt.Font("Segoe UI Historic", 0, 15)); // NOI18N

        rAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        rAdmin.setText("Data Admin");
        rAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAdminActionPerformed(evt);
            }
        });
        jMenu3.add(rAdmin);

        rKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/karyawan.png"))); // NOI18N
        rKaryawan.setText("Data Karyawan");
        rKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(rKaryawan);

        rPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan.png"))); // NOI18N
        rPelanggan.setText("Data Pelanggan");
        rPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(rPelanggan);

        rLayanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rLayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/layanan.png"))); // NOI18N
        rLayanan.setText("Data Layanan");
        rLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLayananActionPerformed(evt);
            }
        });
        jMenu3.add(rLayanan);

        rPengantaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rPengantaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/antar.png"))); // NOI18N
        rPengantaran.setText("Data Pengantaran");
        rPengantaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPengantaranActionPerformed(evt);
            }
        });
        jMenu3.add(rPengantaran);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N
        jMenu4.setText("Logout");
        jMenu4.setFont(new java.awt.Font("Segoe UI Historic", 0, 15)); // NOI18N

        rAkun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        rAkun.setText("Ganti Akun");
        rAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAkunActionPerformed(evt);
            }
        });
        jMenu4.add(rAkun);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAdminActionPerformed
        // TODO add your handling code here:
        master_admin ma = new master_admin();
        ma.setVisible(true);
        ma.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mAdminActionPerformed

    private void mKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKaryawanActionPerformed
        // TODO add your handling code here:
        master_karyawan mk = new master_karyawan();
        mk.setVisible(true);
        mk.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mKaryawanActionPerformed

    private void mPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPelangganActionPerformed
        // TODO add your handling code here:
        master_pelanggan mp = new master_pelanggan();
        mp.setVisible(true);
        mp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mPelangganActionPerformed

    private void mLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLayananActionPerformed
        // TODO add your handling code here:
        master_layanan ml = new master_layanan();
        ml.setVisible(true);
        ml.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mLayananActionPerformed

    private void mAntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAntarActionPerformed
        // TODO add your handling code here:
        master_antar ma = new master_antar();
        ma.setVisible(true);
        ma.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mAntarActionPerformed

    private void mCucimasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCucimasukActionPerformed
        // TODO add your handling code here:
        cucian_masuk cm = new cucian_masuk();
        cm.setVisible(true);
        cm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_mCucimasukActionPerformed

    private void rAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAdminActionPerformed
        // TODO add your handling code here:
        report.report_admin ra = new report.report_admin();
        ra.setVisible(true);
        ra.setLocationRelativeTo(null); 
    }//GEN-LAST:event_rAdminActionPerformed

    private void rKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rKaryawanActionPerformed
        // TODO add your handling code here:
        report.report_karyawan rk = new report.report_karyawan();
        rk.setVisible(true);
        rk.setLocationRelativeTo(null); 
    }//GEN-LAST:event_rKaryawanActionPerformed

    private void rPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPelangganActionPerformed
        // TODO add your handling code here:
        report.report_pelanggan rp = new report.report_pelanggan();
        rp.setVisible(true);
        rp.setLocationRelativeTo(null); 
    }//GEN-LAST:event_rPelangganActionPerformed

    private void rLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLayananActionPerformed
        // TODO add your handling code here:
        report.report_layanan rl = new report.report_layanan();
        rl.setVisible(true);
        rl.setLocationRelativeTo(null); 
    }//GEN-LAST:event_rLayananActionPerformed

    private void rPengantaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPengantaranActionPerformed
        // TODO add your handling code here:
        report.report_antar ra = new report.report_antar();
        ra.setVisible(true);
        ra.setLocationRelativeTo(null); 
    }//GEN-LAST:event_rPengantaranActionPerformed

    private void rAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAkunActionPerformed
        // TODO add your handling code here:
        login lg = new login();
        lg.setVisible(true);
        lg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_rAkunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jam_label;
    private javax.swing.JLabel label_selamatdatang;
    private javax.swing.JMenuItem mAdmin;
    private javax.swing.JMenuItem mAntar;
    private javax.swing.JMenuItem mCucimasuk;
    private javax.swing.JMenuItem mKaryawan;
    private javax.swing.JMenuItem mLayanan;
    private javax.swing.JMenuItem mPelanggan;
    private javax.swing.JMenuItem rAdmin;
    private javax.swing.JMenuItem rAkun;
    private javax.swing.JMenuItem rKaryawan;
    private javax.swing.JMenuItem rLayanan;
    private javax.swing.JMenuItem rPelanggan;
    private javax.swing.JMenuItem rPengantaran;
    private javax.swing.JLabel tanggal_label;
    // End of variables declaration//GEN-END:variables
}